---
# DevOps Test - Task M#1
# Ansible script to install MySQL, nginx and DjangoCMS.
# Create new user for DjangoCMS
# Upload installed DjangoCMS application code to a new repo in GitHub
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  
  vars_files:
  - vars/mysql-root.yml
  
  tasks:
  - name: Install MySQL, MySQL DB and nginx
    apt: pkg={{ item }} state=installed update_cache=true
 	with_items:
	  - mysql-server
	  - python-mysqldb
	  - nginx
	  
  - name: Start MySQL on boot
    service: name=mysql enabled=yes state=started
	
- include: django-install.yml
- include: run-django-cms.yml